import React, { useMemo, useState } from 'react';
import { ArrowLeft, ChevronRight, Heart, Home } from 'lucide-react';
import { POCO_CATEGORIES, getProductsByBrand } from '../domain/shop/productCatalog';
import { BRANDS, getBrandById } from '../domain/shop/brands';
import { useFinance } from '../context/FinanceContext';

const tagLabel = { new: 'NEW', popular: '人気', recommended: 'おすすめ' };
const Coin = ({ value }) => <span className="inline-flex items-center gap-1 font-black text-[#d9762a]">● {value.toLocaleString()}</span>;
const BackButton = ({ onClick, label = '戻る' }) => <button type="button" onClick={onClick} className="rounded-full p-2 text-[#315d52] transition hover:bg-[#edf3ed]" aria-label={label}><ArrowLeft className="h-5 w-5" /></button>;
const BrandLogo = ({ brand, className = '' }) => brand.logo ? <img src={brand.logo} alt={brand.name} className={`h-auto w-auto object-contain ${className}`} /> : <span className={`font-black tracking-[.18em] ${className}`}>{brand.name}</span>;

const ProductVisual = ({ product, large = false }) => (
  <div className={`relative flex items-center justify-center overflow-hidden bg-gradient-to-br from-[#f9e9d2] via-[#f4d9b7] to-[#bad7c9] ${large ? 'aspect-[1.04]' : 'aspect-square'}`}>
    <span className="absolute -right-8 -top-8 h-28 w-28 rounded-full bg-white/30" />
    {typeof product.image === 'string' && (product.image.startsWith('/') || product.image.startsWith('http') || /\.(png|jpe?g|webp|gif|svg)$/i.test(product.image)) ? (
      <img
        src={product.image}
        alt={product.name}
        className={`relative block h-full w-full object-contain drop-shadow-[0_12px_10px_rgba(91,61,34,.25)] ${large ? 'p-6' : 'p-3'}`}
      />
    ) : (
      <span className={`relative leading-none ${large ? 'text-8xl' : 'text-5xl'}`}>{product.image}</span>
    )}
  </div>
);const ProductCard = ({ product, favorite, onFavorite, onOpen }) => <article className="relative overflow-hidden rounded-2xl border border-[#e9dac5] bg-white shadow-sm"><button type="button" onClick={() => onOpen(product)} className="block w-full text-left" aria-label={`${product.name}の詳細を見る`}><ProductVisual product={product} /></button><button type="button" onClick={() => onFavorite(product.id)} className="absolute right-2 top-2 rounded-full bg-white/90 p-2 text-[#45433e] shadow-sm" aria-label={`${product.name}をお気に入り`}><Heart className={`h-4 w-4 ${favorite ? 'fill-[#d9762a] text-[#d9762a]' : ''}`} /></button>{product.tags[0] && <span className="absolute left-2 top-2 rounded-full bg-[#315d52] px-2 py-1 text-[10px] font-black text-white">{tagLabel[product.tags[0]]}</span>}<button type="button" onClick={() => onOpen(product)} className="block w-full p-3 text-left"><h3 className="min-h-10 text-sm font-black leading-snug text-[#292b28]">{product.name}</h3><Coin value={product.price} /></button></article>;

const BrandCard = ({ brand, onSelect }) => {
  const available = brand.status === 'available';
  return <article className="overflow-hidden rounded-[1.75rem] border border-[#e8dac6] bg-white shadow-sm"><button type="button" onClick={() => available && onSelect(brand)} disabled={!available} className={`group block w-full text-left ${available ? 'cursor-pointer' : 'cursor-default'}`} aria-label={available ? `${brand.name}のショップを開く` : `${brand.name}は準備中`}><div className={`relative aspect-[1.82/1] overflow-hidden ${brand.heroImage ? 'bg-[#d9c2a4]' : 'bg-gradient-to-br from-[#d8ddd9] via-[#f1ede4] to-[#c8b79f]'}`}>{brand.heroImage ? <img src={brand.heroImage} alt={`${brand.name} ブランドイメージ`} className="h-full w-full object-cover transition duration-500 group-hover:scale-[1.035]" /> : <div className="absolute inset-0 bg-[radial-gradient(circle_at_75%_30%,rgba(255,255,255,.75),transparent_22%),radial-gradient(circle_at_18%_80%,rgba(255,255,255,.5),transparent_28%)]" />}<div className="absolute inset-0 bg-gradient-to-t from-black/45 via-black/5 to-transparent" />{brand.status === 'coming-soon' && <span className="absolute right-4 top-4 rounded-full bg-[#292b28]/90 px-3 py-1.5 text-[10px] font-black tracking-[.14em] text-white">COMING SOON</span>}</div><div className="p-5"><div className="flex items-start justify-between gap-4"><div><BrandLogo brand={brand} className="max-h-8 max-w-36 text-xl text-[#292b28]" /><p className="mt-3 text-sm font-bold leading-relaxed text-[#64665f]">{brand.tagline}</p></div>{available && <ChevronRight className="mt-1 h-5 w-5 shrink-0 text-[#315d52] transition group-hover:translate-x-1" />}</div><p className="mt-4 text-sm font-black text-[#d9762a]"><Coin value={brand.minPrice} /> <span className="mx-1 text-[#a4998a]">–</span> <Coin value={brand.maxPrice} /></p></div></button></article>;
};

export const Shop = ({ onBack }) => {
  const { game, buyProduct, toggleFavoriteProduct, placeOwnedFurniture } = useFinance();
  const products = useMemo(() => getProductsByBrand('poco'), []);
  const pocoBrand = getBrandById('poco');
  const [view, setView] = useState('brands');
  const [category, setCategory] = useState(null);
  const [selectedProduct, setSelectedProduct] = useState(null);
  const [purchasedProduct, setPurchasedProduct] = useState(null);
  const favorites = game.favoriteProductIds ?? [];
  const openProduct = (product) => { setSelectedProduct(product); setView('detail'); };
  const favorite = (productId) => toggleFavoriteProduct(productId);
  const purchase = () => { const result = buyProduct(selectedProduct.id); if (result.ok) { setPurchasedProduct(result.product); setView('complete'); } };
  const goHome = () => { setCategory(null); setSelectedProduct(null); setView('home'); };
  const renderCards = (items, className = 'flex gap-3 overflow-x-auto pb-2') => <div className={className}>{items.map((product) => <div key={product.id} className={className.includes('grid') ? '' : 'w-40 shrink-0'}><ProductCard product={product} favorite={favorites.includes(product.id)} onFavorite={favorite} onOpen={openProduct} /></div>)}</div>;

  if (view === 'brands') return <div className="min-h-[100dvh] bg-[#f8f5ee] text-[#292b28]"><main className="mx-auto w-full max-w-md px-4 pb-10 pt-5 sm:px-5"><header className="flex items-center gap-3"><BackButton onClick={onBack} label="ホームに戻る" /><div className="flex-1"><p className="text-[10px] font-black tracking-[.2em] text-[#738476]">IN-GAME SHOP</p><h1 className="text-2xl font-black">ブランドを選ぶ</h1></div><div className="rounded-xl bg-[#315d52] px-3 py-2 text-right text-white"><span className="block text-[10px] font-bold text-white/70">所持コイン</span><span className="text-sm font-black">● {game.money.toLocaleString()}</span></div></header><p className="mt-7 text-sm font-bold leading-relaxed text-[#64665f]">お気に入りのブランドから、暮らしを彩るアイテムを探そう。</p><section className="mt-5 space-y-5" aria-label="ブランド一覧">{BRANDS.map((brand) => <BrandCard key={brand.id} brand={brand} onSelect={goHome} />)}</section></main></div>;

  if (view === 'category') { const categoryData = POCO_CATEGORIES.find((item) => item.id === category); const categoryProducts = products.filter((product) => product.category === category); return <div className="min-h-[100dvh] bg-[#f8f5ee] text-[#292b28]"><main className="mx-auto w-full max-w-md px-4 pb-10 pt-5 sm:px-5"><header className="flex items-center gap-2"><BackButton onClick={goHome} /><div className="flex-1"><p className="text-[10px] font-black tracking-[.18em] text-[#738476]">POCO / CATEGORY</p><h1 className="text-2xl font-black">{categoryData?.name}</h1></div><div className="rounded-xl bg-white px-3 py-2 text-xs shadow-sm"><Coin value={game.money} /></div></header><div className="mt-6 flex items-center justify-between"><p className="text-sm font-bold text-[#6b7067]">{categoryData?.description}</p><span className="rounded-full border border-[#d8d2c4] px-3 py-1 text-xs font-bold">{categoryProducts.length} items</span></div><section className="mt-4">{renderCards(categoryProducts, 'grid grid-cols-2 gap-3')}</section></main></div>; }
  if (view === 'detail' && selectedProduct) { const missing = Math.max(selectedProduct.price - game.money, 0); const progress = Math.min((game.money / selectedProduct.price) * 100, 100); return <div className="min-h-[100dvh] bg-[#f8f5ee] text-[#292b28]"><main className="mx-auto w-full max-w-md pb-8"><header className="flex items-center gap-2 px-4 pt-5 sm:px-5"><BackButton onClick={() => category ? setView('category') : goHome()} /><span className="flex-1"><img src={pocoBrand.logo} alt={pocoBrand.name} className="h-auto w-auto max-w-20 object-contain" /></span><button type="button" onClick={() => favorite(selectedProduct.id)} className="rounded-full p-2" aria-label="お気に入り"><Heart className={`h-5 w-5 ${favorites.includes(selectedProduct.id) ? 'fill-[#d9762a] text-[#d9762a]' : 'text-[#315d52]'}`} /></button></header><div className="mt-4"><ProductVisual product={selectedProduct} large /></div><div className="px-5 pt-6"><img src={pocoBrand.logo} alt={pocoBrand.name} className="h-auto w-auto max-w-16 object-contain" /><h1 className="mt-2 text-2xl font-black">{selectedProduct.name}</h1><p className="mt-3 text-xl"><Coin value={selectedProduct.price} /></p><p className="mt-5 text-sm font-bold leading-relaxed text-[#60635e]">{selectedProduct.description}</p><section className="mt-6 rounded-2xl bg-white p-4 shadow-sm"><p className="text-xs font-black text-[#738476]">あなたの所持金</p><p className="mt-1 text-lg"><Coin value={game.money} /></p><div className="mt-4 flex justify-between text-xs font-bold"><span>{game.money.toLocaleString()} / {selectedProduct.price.toLocaleString()}</span><span>{missing ? `あと ${missing.toLocaleString()} コインで買える！` : '今すぐ購入できます'}</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-[#e9e2d5]"><div className="h-full rounded-full bg-[#d9762a] transition-all" style={{ width: `${progress}%` }} /></div></section><button type="button" disabled={missing > 0} onClick={purchase} className="mt-5 w-full rounded-2xl bg-[#315d52] py-4 font-black text-white shadow-lg shadow-[#315d52]/20 transition hover:bg-[#244b40] disabled:cursor-not-allowed disabled:bg-[#b9b8ae]">{missing ? `あと ${missing.toLocaleString()} コインで購入できます` : '購入する'}</button></div></main></div>; }
  if (view === 'complete' && purchasedProduct) return <div className="min-h-[100dvh] bg-[#f8f5ee] text-[#292b28]"><main className="mx-auto flex min-h-[100dvh] w-full max-w-md flex-col justify-center px-5 text-center"><div className="mx-auto w-full max-w-64 overflow-hidden rounded-3xl shadow-sm"><ProductVisual product={purchasedProduct} large /></div><p className="mt-6 text-xs font-black tracking-[.2em] text-[#738476]">POCO HOME</p><h1 className="mt-2 text-3xl font-black">購入しました！</h1><p className="mt-2 text-lg font-bold">{purchasedProduct.name}</p><p className="mt-3 text-sm font-bold text-[#6b7067]">部屋で好きな場所に動かしてみましょう。</p><button type="button" onClick={() => { placeOwnedFurniture(purchasedProduct.id); onBack(); }} className="mt-8 rounded-2xl bg-[#315d52] py-4 font-black text-white">今すぐ配置する</button><button type="button" onClick={goHome} className="mt-3 rounded-2xl border border-[#315d52] py-4 font-black text-[#315d52]">ショップに戻る</button></main></div>;

  const recommended = products.filter((product) => product.tags.includes('recommended')); const newProducts = products.filter((product) => product.tags.includes('new')); const popular = products.filter((product) => product.tags.includes('popular'));
  return <div className="min-h-[100dvh] bg-[#f8f5ee] text-[#292b28]"><main className="mx-auto w-full max-w-md px-4 pb-12 pt-5 sm:px-5"><header className="flex items-center gap-3"><BackButton onClick={() => setView('brands')} /><div className="flex-1"><p className="text-xs font-black tracking-[.22em] text-[#d9762a]">LIVING, MADE EASY</p><img src={pocoBrand.logo} alt={pocoBrand.name} className="mt-1 h-auto w-auto max-w-24 object-contain" /></div><div className="rounded-xl bg-white px-3 py-2 text-right shadow-sm"><span className="block text-[10px] font-bold text-[#738476]">所持コイン</span><Coin value={game.money} /></div><Heart className="h-5 w-5 text-[#315d52]" aria-label="お気に入り" /></header><section className="mt-6"><h2 className="text-lg font-black">カテゴリから探す</h2><div className="mt-3 flex gap-3 overflow-x-auto pb-2">{POCO_CATEGORIES.map((item) => <button key={item.id} type="button" onClick={() => { setCategory(item.id); setView('category'); }} className="w-24 shrink-0 overflow-hidden rounded-2xl border border-[#e5d9c6] bg-white text-left shadow-sm"><div className="flex aspect-square items-center justify-center bg-[#e5f0e7] text-4xl">{item.image}</div><span className="block px-2 py-2 text-center text-xs font-black">{item.name}</span></button>)}</div></section><button type="button" onClick={() => { setCategory('sofa'); setView('category'); }} className="relative mt-7 block min-h-60 w-full overflow-hidden rounded-[2rem] bg-gradient-to-br from-[#d8a36d] via-[#c7d7bc] to-[#6e9a87] p-6 text-left text-white"><span className="absolute bottom-4 right-6 text-9xl">🛋️</span><span className="absolute right-32 top-8 text-5xl">🪴</span><span className="absolute bottom-12 left-9 text-5xl">🧶</span><p className="relative text-xs font-black tracking-[.2em] text-white/80">POCO ROOM IDEA</p><h2 className="relative mt-2 max-w-52 text-2xl font-black leading-tight">好きなものを、気軽に重ねる部屋。</h2><span className="relative mt-5 inline-flex items-center gap-1 rounded-full bg-white/90 px-3 py-2 text-xs font-black text-[#315d52]">部屋をのぞく <ChevronRight className="h-4 w-4" /></span></button><section className="mt-8"><h2 className="text-xl font-black">おすすめ</h2><div className="mt-3">{renderCards(recommended)}</div></section><section className="mt-7"><h2 className="text-xl font-black">NEW</h2><div className="mt-3">{renderCards(newProducts)}</div></section><section className="mt-7"><h2 className="text-xl font-black">人気アイテム</h2><div className="mt-3">{renderCards(popular)}</div></section><section className="mt-8 rounded-2xl bg-[#e5f0e7] p-4"><div className="flex items-center gap-3"><Home className="h-5 w-5 text-[#315d52]" /><div><h2 className="font-black">購入した家具</h2><p className="text-xs font-bold text-[#667068]">部屋には購入数まで配置できます</p></div></div><p className="mt-3 text-sm font-bold text-[#315d52]">{game.ownedFurniture.reduce((total, item) => total + item.quantity, 0)} 点を所持中</p></section></main></div>;
};
